# Generated by Django 4.2.19 on 2025-02-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='mood',
            field=models.CharField(choices=[('happy', 'Happy 😊'), ('neutral', 'Neutral 😐'), ('sad', 'Sad 😢'), ('angry', 'Angry 😠'), ('stressed', 'Stressed 😟')], max_length=20),
        ),
    ]
